apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rx-producer-deployment
  labels:
    app: rx-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rx-producer
  template:
    metadata:
      labels:
        app: rx-producer
    spec:
      containers:
      - name: rx-producer
        image: docker.artifactory.surescripts.local/gaden/innovation-days/rxproducer:0.1